// Generated by initialization/gg_to_mem.py -- do not edit.
// Widths and offsets for the .mem images, plus the scalar
// grid-graph constants (which are not worth a memory).
//
// Route box (DBU): 176400 147000 200260 176400
// Node state: dumpSearchGraph() snapshot of search 2 --
// 3605 guide, 1 src, 1 dst nodes.

localparam integer GG_X_DIM      = 130;
localparam integer GG_Y_DIM      = 142;
localparam integer GG_Z_DIM      = 10;
localparam integer GG_NUM_NODES  = 184600;
localparam integer GG_ADDR_BITS  = 18;
// addr = (z * GG_Y_DIM + y) * GG_X_DIM + x

// ---- gg_nodes.mem ----
// x/y/z are recoverable from the address above, so the word is
// state [23:0] plus the A* scratch the search writes back.
localparam integer GG_NODE_BITS  = 28;
localparam integer GG_STATE_W    = 24;
localparam integer GG_BIT_CLOSED = 24;
localparam integer GG_DIR_LSB    = 25;
localparam integer GG_DIR_BITS   = 3;
// Both scratch fields are 0 in this image: on entry to search()
// no node is closed and every prevAstarNodeDir is UNKNOWN.
localparam [2:0] GG_DIR_UNKNOWN  = 3'd0;
localparam [2:0] GG_DIR_D        = 3'd1;
localparam [2:0] GG_DIR_S        = 3'd2;
localparam [2:0] GG_DIR_W        = 3'd3;
localparam [2:0] GG_DIR_E        = 3'd4;
localparam [2:0] GG_DIR_N        = 3'd5;
localparam [2:0] GG_DIR_U        = 3'd6;

localparam integer GG_BIT_hasEastEdge              = 0;
localparam integer GG_BIT_hasNorthEdge             = 1;
localparam integer GG_BIT_hasUpEdge                = 2;
localparam integer GG_BIT_isBlockedEast            = 3;
localparam integer GG_BIT_isBlockedNorth           = 4;
localparam integer GG_BIT_isBlockedUp              = 5;
localparam integer GG_BIT_hasSpecialVia            = 6;
localparam integer GG_BIT_overrideShapeCostVia     = 7;
localparam integer GG_BIT_hasGridCostEast          = 8;
localparam integer GG_BIT_hasGridCostNorth         = 9;
localparam integer GG_BIT_hasGridCostUp            = 10;
localparam integer GG_BIT_hasApCostEast            = 11;
localparam integer GG_BIT_hasApCostNorth           = 12;
localparam integer GG_BIT_hasApCostUp              = 13;
localparam integer GG_BIT_routeShapeCostPlanar     = 14;
localparam integer GG_BIT_routeShapeCostVia        = 15;
localparam integer GG_BIT_markerCostPlanar         = 16;
localparam integer GG_BIT_markerCostVia            = 17;
localparam integer GG_BIT_fixedShapeCostVia        = 18;
localparam integer GG_BIT_fixedShapeCostPlanarHorz = 19;
localparam integer GG_BIT_fixedShapeCostPlanarVert = 20;
localparam integer GG_BIT_guide                    = 21;
localparam integer GG_BIT_src                      = 22;
localparam integer GG_BIT_dst                      = 23;

// ---- gg_{x,y,z}coords.mem ----
// Signed two's complement DBU.  One width for all three axes so
// the getEstCost datapath needs no per-axis sign extension.
localparam integer GG_COORD_BITS = 20;

// ---- via*_forbidden_*.mem ----
// Each word is GG_FORBID_SLOTS {lo, hi} pairs, slot 0 in the high
// bits; slot s occupies [GG_FORBID_PAIR*(GG_FORBID_SLOTS-s) - 1 :
// GG_FORBID_PAIR*(GG_FORBID_SLOTS-1-s)].  An entry needs more than
// one slot when its forbidden lengths are disjoint.
localparam integer GG_FORBID_SLOTS  = 2;
localparam integer GG_FORBID_PAIR   = 24;
localparam integer GG_FORBID_BITS   = 48;
localparam integer GG_FORBID_HALF   = 12;  // within a pair: lo = [23:12], hi = [11:0]
localparam integer GG_V2V_ENTRIES   = 80;
localparam integer GG_TURN_ENTRIES  = 40;
// forbidden when lo <= len <= hi in ANY slot; unused slot is
// lo=all-ones, hi=0, which no len can satisfy

localparam integer GG_DRCCOST          = 8;
localparam integer GG_MARKERCOST       = 0;
localparam integer GG_FIXEDSHAPECOST   = 8;
localparam integer GG_GRIDCOST         = 2;
localparam integer GG_BLOCKCOST        = 32;
localparam integer GG_GUIDECOST        = 1;

// ---- gg_layers.mem ----
// Per-layer constants, indexed by z.  A memory rather than
// localparams so the direction and minWidth are readable at
// runtime with the z the datapath already has, instead of a
// 10-way case that has to be re-elaborated per design.
// Direction is the raw odb::dbTechLayerDir enum; the dump's own
// column header mislabels it as 0=H/1=V/2=NONE -- ignore it.
localparam integer GG_LAYER_BITS     = 16;
localparam integer GG_MINWIDTH_BITS  = 12;  // [11:0]
localparam integer GG_LAYER_DIR_LSB  = 12;
localparam integer GG_LAYER_DIR_BITS = 2;
localparam [1:0] GG_LAYER_DIR_NONE       = 2'd0;
localparam [1:0] GG_LAYER_DIR_HORIZONTAL = 2'd1;
localparam [1:0] GG_LAYER_DIR_VERTICAL   = 2'd2;
// per-z values, for reference -- read them from the .mem, not here:
//   dir      H V H V H V H V H V
//   minWidth 140 140 140 280 280 280 800 800 1600 1600

// frLayerNum per z, for tracing back to the LEF; not needed at runtime
localparam integer GG_LAYERNUM_0    = 2;
localparam integer GG_LAYERNUM_1    = 4;
localparam integer GG_LAYERNUM_2    = 6;
localparam integer GG_LAYERNUM_3    = 8;
localparam integer GG_LAYERNUM_4    = 10;
localparam integer GG_LAYERNUM_5    = 12;
localparam integer GG_LAYERNUM_6    = 14;
localparam integer GG_LAYERNUM_7    = 16;
localparam integer GG_LAYERNUM_8    = 18;
localparam integer GG_LAYERNUM_9    = 20;
