// Generated by initialization/gg_to_mem.py -- do not edit.
// Route box (DBU): 50400 50400 79800 79800
// Goal box (maze idx): 148 24 0 .. 148 36 0 -- dstBox of search 3 in search_iter1_x50400_y50400_s3.txt
// Widths, bit offsets and table layouts are not here; each
// .mem file documents its own word in its header.

// Coordinates for grid and cost size, change when grid graph changes
  parameter GRID_I = 182;
  parameter GRID_J = 154;
  parameter GRID_K = 10;
  parameter ITER = 1;

  parameter LOWER_GOAL_X = 77710;
  parameter LOWER_GOAL_Y = 53620;
  parameter LOWER_GOAL_Z = 1120;

  parameter UPPER_GOAL_X = 77710;
  parameter UPPER_GOAL_Y = 55580;
  parameter UPPER_GOAL_Z = 1120;

  // Constants for Tritonroute
  parameter DRC_COST = 8;
  parameter MARKER_COST = 8;
  parameter FIXEDSHAPECOST = 8;
  parameter GRID_COST = 2;
  parameter BLOCK_COST = 32;
  parameter GUIDE_COST = 1;

  parameter USE_NONPREF_TRACKS = 1;
  parameter BOTTOM_ROUTING_LAYER = 1; //layer_num of 4 or layer z of 1
  parameter TOP_ROUTING_LAYER = 9; //layer_num of 20 or layer z of 9
